backend:
  name: github
  repo: MDSFPRO/MDS  # Remplace par ton user/repo exact
  branch: main
  auth_scope: repo
  client_id: Ov23liwhmOiAU2pbnIb8  # Copie ici le Client ID de ton App OAuth

media_folder: "images/articles"
public_folder: "/images/articles"

collections:
  - name: "conseil"
    label: "Conseils IT"
    folder: "articles/conseil"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image d’illustration", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Catégorie", name: "category", widget: "hidden", default: "Conseil IT" }
  - name: "actu"
    label: "Actualités"
    folder: "articles/actu"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image d’illustration", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Catégorie", name: "category", widget: "hidden", default: "Actualité" }
